In [32]:
import numpy as np
import pandas as pd
import hypertools as hyp 

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, mean_absolute_error, mean_squared_error

In [19]:
data = pd.read_csv('YearPredictionMSD.csv', header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
0,2001,49.94357,21.47114,73.07750,8.74861,-17.40628,-13.09905,-25.01202,-12.23257,7.83089,...,13.01620,-54.40548,58.99367,15.37344,1.11144,-23.08793,68.40795,-1.82223,-27.46348,2.26327
1,2001,48.73215,18.42930,70.32679,12.94636,-10.32437,-24.83777,8.76630,-0.92019,18.76548,...,5.66812,-19.68073,33.04964,42.87836,-9.90378,-32.22788,70.49388,12.04941,58.43453,26.92061
2,2001,50.95714,31.85602,55.81851,13.41693,-6.57898,-18.54940,-3.27872,-2.35035,16.07017,...,3.03800,26.05866,-50.92779,10.93792,-0.07568,43.20130,-115.00698,-0.05859,39.67068,-0.66345
3,2001,48.24750,-1.89837,36.29772,2.58776,0.97170,-26.21683,5.05097,-10.34124,3.55005,...,34.57337,-171.70734,-16.96705,-46.67617,-12.51516,82.58061,-72.08993,9.90558,199.62971,18.85382
4,2001,50.97020,42.20998,67.09964,8.46791,-15.85279,-16.81409,-12.48207,-9.37636,12.63699,...,9.92661,-55.95724,64.92712,-17.72522,-1.49237,-7.50035,51.76631,7.88713,55.66926,28.74903

In [20]:
data.columns = ["year"] + ["timb_avg" + str(i) for i in range(12)] + ["timb_cov" + str(i) for i in range(78)]
data.head()

,year,timb_avg0,timb_avg1,timb_avg2,timb_avg3,timb_avg4,timb_avg5,timb_avg6,timb_avg7,timb_avg8,...,timb_cov68,timb_cov69,timb_cov70,timb_cov71,timb_cov72,timb_cov73,timb_cov74,timb_cov75,timb_cov76,timb_cov77
0,2001,49.94357,21.47114,73.07750,8.74861,-17.40628,-13.09905,-25.01202,-12.23257,7.83089,...,13.01620,-54.40548,58.99367,15.37344,1.11144,-23.08793,68.40795,-1.82223,-27.46348,2.26327
1,2001,48.73215,18.42930,70.32679,12.94636,-10.32437,-24.83777,8.76630,-0.92019,18.76548,...,5.66812,-19.68073,33.04964,42.87836,-9.90378,-32.22788,70.49388,12.04941,58.43453,26.92061
2,2001,50.95714,31.85602,55.81851,13.41693,-6.57898,-18.54940,-3.27872,-2.35035,16.07017,...,3.03800,26.05866,-50.92779,10.93792,-0.07568,43.20130,-115.00698,-0.05859,39.67068,-0.66345
3,2001,48.24750,-1.89837,36.29772,2.58776,0.97170,-26.21683,5.05097,-10.34124,3.55005,...,34.57337,-171.70734,-16.96705,-46.67617,-12.51516,82.58061,-72.08993,9.90558,199.62971,18.85382
4,2001,50.97020,42.20998,67.09964,8.46791,-15.85279,-16.81409,-12.48207,-9.37636,12.63699,...,9.92661,-55.95724,64.92712,-17.72522,-1.49237,-7.50035,51.76631,7.88713,55.66926,28.74903

In [21]:
data = data[data['year'] > 1964]
data = data[data['year'] < 2011]
data.head()

def bootstrap(data, num_to_extract=1000):
    # This function will be applied on each group of instances of the same
    # class in `data`.
    def sampleClass(classgroup):
        cls = classgroup['year'].iloc[0]
        nDesired = num_to_extract
        nRows = len(classgroup)

        nSamples = min(nRows, nDesired)
        return classgroup.sample(nSamples)

    samples = data.groupby('year').apply(sampleClass)
    
    return samples

data = bootstrap(data)

In [29]:
data.ix[data.year < 1978, 'result'] = 0
data.ix[(data.year > 1977) & (data.year < 1990), 'result'] = 1
data.ix[(data.year > 1989) & (data.year < 2011), 'result'] = 2

labelEncoder = preprocessing.LabelEncoder()
data['result'] = labelEncoder.fit_transform(data['result'])

In [24]:
X = data.drop('year', axis=1)
X = data.drop('result', axis=1)
Y = data['year']
Z = data['result']

pca = PCA(n_components=0.99, svd_solver='full')

X = pca.fit_transform(X)
print(X.shape)

X_train, X_test, Y_train, Y_test = train_test_split(X, Z, test_size=0.3, random_state=101)

(46000, 45)

In [33]:
keys = []
scores = []

mod = LogisticRegression()
mod.fit(X_train, Y_train)
print("Done Training")

Done Training

In [34]:
pred = mod.predict(X_test)
print("Done Predicting")

Done Predicting

In [35]:
print pred.shape

(13800,)

In [36]:
print('Results for: \n')

pred_test = [int(round(i)) for i in pred ]

print(confusion_matrix(Y_test, pred_test))
print(classification_report(Y_test, pred_test))
acc = accuracy_score(Y_test, pred_test)
print(acc)
print('\n' + '\n')

Results for:

[[1459  347 2120]
 [ 563  936 2063]
 [ 851  474 4987]]
             precision    recall  f1-score   support

        0.0       0.51      0.37      0.43      3926
        1.0       0.53      0.26      0.35      3562
        2.0       0.54      0.79      0.64      6312

avg / total       0.53      0.53      0.51     13800

0.534927536232

In [37]:
print(mean_absolute_error(Y_test, pred_test))

0.680362318841

In [38]:
print(mean_squared_error(Y_test, pred_test)**0.5)

1.05401234764

In [26]:
result = data.groupby(['year']).agg(['count'])
pd.set_option('display.max_rows', len(result))
print(result)
pd.reset_option('display.max_rows')

     timb_avg0 timb_avg1 timb_avg2 timb_avg3 timb_avg4 timb_avg5 timb_avg6  \
         count     count     count     count     count     count     count
year
1922         6         6         6         6         6         6         6
1924         5         5         5         5         5         5         5
1925         7         7         7         7         7         7         7
1926        19        19        19        19        19        19        19
1927        42        42        42        42        42        42        42
1928        52        52        52        52        52        52        52
1929        93        93        93        93        93        93        93
1930        40        40        40        40        40        40        40
1931        35        35        35        35        35        35        35
1932        11        11        11        11        11        11        11
1933         6         6         6         6         6         6         6
1934        29        29        29        29        29        29        29
1935        24        24        24        24        24        24        24
1936        25        25        25        25        25        25        25
1937        28        28        28        28        28        28        28
1938        19        19        19        19        19        19        19
1939        35        35        35        35        35        35        35
1940        52        52        52        52        52        52        52
1941        32        32        32        32        32        32        32
1942        24        24        24        24        24        24        24
1943        14        14        14        14        14        14        14
1944        15        15        15        15        15        15        15
1945        30        30        30        30        30        30        30
1946        29        29        29        29        29        29        29
1947        57        57        57        57        57        57        57
1948        43        43        43        43        43        43        43
1949        60        60        60        60        60        60        60
1950        83        83        83        83        83        83        83
1951        74        74        74        74        74        74        74
1952        77        77        77        77        77        77        77
1953       133       133       133       133       133       133       133
1954       123       123       123       123       123       123       123
1955       275       275       275       275       275       275       275
1956       565       565       565       565       565       565       565
1957       597       597       597       597       597       597       597
1958       583       583       583       583       583       583       583
1959       592       592       592       592       592       592       592
1960       424       424       424       424       424       424       424
1961       571       571       571       571       571       571       571
1962       605       605       605       605       605       605       605
1963       902       902       902       902       902       902       902
1964       945       945       945       945       945       945       945
1965      1120      1120      1120      1120      1120      1120      1120
1966      1377      1377      1377      1377      1377      1377      1377
1967      1718      1718      1718      1718      1718      1718      1718
1968      1867      1867      1867      1867      1867      1867      1867
1969      2210      2210      2210      2210      2210      2210      2210
1970      2349      2349      2349      2349      2349      2349      2349
1971      2131      2131      2131      2131      2131      2131      2131
1972      2288      2288      2288      2288      2288      2288      2288
1973      2596      2596      2596      2596      2596      2596      2596
1974      2184      2184      2184      2184      2184      2184      2184
1975      2482      2482      2482      2482      2482      2482      2482
1976      2179      2179      2179      2179      2179      2179      2179
1977      2502      2502      2502      2502      2502      2502      2502
1978      2926      2926      2926      2926      2926      2926      2926
1979      3108      3108      3108      3108      3108      3108      3108
1980      3101      3101      3101      3101      3101      3101      3101
1981      3162      3162      3162      3162      3162      3162      3162
1982      3597      3597      3597      3597      3597      3597      3597
1983      3386      3386      3386      3386      3386      3386      3386
1984      3368      3368      3368      3368      3368      3368      3368
1985      3578      3578      3578      3578      3578      3578      3578
1986      4219      4219      4219      4219      4219      4219      4219
1987      5122      5122      5122      5122      5122      5122      5122
1988      5611      5611      5611      5611      5611      5611      5611
1989      6670      6670      6670      6670      6670      6670      6670
1990      7256      7256      7256      7256      7256      7256      7256
1991      8647      8647      8647      8647      8647      8647      8647
1992      9543      9543      9543      9543      9543      9543      9543
1993     10525     10525     10525     10525     10525     10525     10525
1994     12121     12121     12121     12121     12121     12121     12121
1995     13257     13257     13257     13257     13257     13257     13257
1996     14130     14130     14130     14130     14130     14130     14130
1997     15182     15182     15182     15182     15182     15182     15182
1998     15814     15814     15814     15814     15814     15814     15814
1999     18238     18238     18238     18238     18238     18238     18238
2000     19285     19285     19285     19285     19285     19285     19285
2001     21590     21590     21590     21590     21590     21590     21590
2002     23451     23451     23451     23451     23451     23451     23451
2003     27382     27382     27382     27382     27382     27382     27382
2004     29607     29607     29607     29607     29607     29607     29607
2005     34952     34952     34952     34952     34952     34952     34952
2006     37534     37534     37534     37534     37534     37534     37534
2007     39404     39404     39404     39404     39404     39404     39404
2008     34760     34760     34760     34760     34760     34760     34760
2009     31038     31038     31038     31038     31038     31038     31038
2010      9396      9396      9396      9396      9396      9396      9396
2011         1         1         1         1         1         1         1

     timb_avg7 timb_avg8 timb_avg9    ...     timb_cov68 timb_cov69  \
         count     count     count    ...          count      count
year                                  ...
1922         6         6         6    ...              6          6
1924         5         5         5    ...              5          5
1925         7         7         7    ...              7          7
1926        19        19        19    ...             19         19
1927        42        42        42    ...             42         42
1928        52        52        52    ...             52         52
1929        93        93        93    ...             93         93
1930        40        40        40    ...             40         40
1931        35        35        35    ...             35         35
1932        11        11        11    ...             11         11
1933         6         6         6    ...              6          6
1934        29        29        29    ...             29         29
1935        24        24        24    ...             24         24
1936        25        25        25    ...             25         25
1937        28        28        28    ...             28         28
1938        19        19        19    ...             19         19
1939        35        35        35    ...             35         35
1940        52        52        52    ...             52         52
1941        32        32        32    ...             32         32
1942        24        24        24    ...             24         24
1943        14        14        14    ...             14         14
1944        15        15        15    ...             15         15
1945        30        30        30    ...             30         30
1946        29        29        29    ...             29         29
1947        57        57        57    ...             57         57
1948        43        43        43    ...             43         43
1949        60        60        60    ...             60         60
1950        83        83        83    ...             83         83
1951        74        74        74    ...             74         74
1952        77        77        77    ...             77         77
1953       133       133       133    ...            133        133
1954       123       123       123    ...            123        123
1955       275       275       275    ...            275        275
1956       565       565       565    ...            565        565
1957       597       597       597    ...            597        597
1958       583       583       583    ...            583        583
1959       592       592       592    ...            592        592
1960       424       424       424    ...            424        424
1961       571       571       571    ...            571        571
1962       605       605       605    ...            605        605
1963       902       902       902    ...            902        902
1964       945       945       945    ...            945        945
1965      1120      1120      1120    ...           1120       1120
1966      1377      1377      1377    ...           1377       1377
1967      1718      1718      1718    ...           1718       1718
1968      1867      1867      1867    ...           1867       1867
1969      2210      2210      2210    ...           2210       2210
1970      2349      2349      2349    ...           2349       2349
1971      2131      2131      2131    ...           2131       2131
1972      2288      2288      2288    ...           2288       2288
1973      2596      2596      2596    ...           2596       2596
1974      2184      2184      2184    ...           2184       2184
1975      2482      2482      2482    ...           2482       2482
1976      2179      2179      2179    ...           2179       2179
1977      2502      2502      2502    ...           2502       2502
1978      2926      2926      2926    ...           2926       2926
1979      3108      3108      3108    ...           3108       3108
1980      3101      3101      3101    ...           3101       3101
1981      3162      3162      3162    ...           3162       3162
1982      3597      3597      3597    ...           3597       3597
1983      3386      3386      3386    ...           3386       3386
1984      3368      3368      3368    ...           3368       3368
1985      3578      3578      3578    ...           3578       3578
1986      4219      4219      4219    ...           4219       4219
1987      5122      5122      5122    ...           5122       5122
1988      5611      5611      5611    ...           5611       5611
1989      6670      6670      6670    ...           6670       6670
1990      7256      7256      7256    ...           7256       7256
1991      8647      8647      8647    ...           8647       8647
1992      9543      9543      9543    ...           9543       9543
1993     10525     10525     10525    ...          10525      10525
1994     12121     12121     12121    ...          12121      12121
1995     13257     13257     13257    ...          13257      13257
1996     14130     14130     14130    ...          14130      14130
1997     15182     15182     15182    ...          15182      15182
1998     15814     15814     15814    ...          15814      15814
1999     18238     18238     18238    ...          18238      18238
2000     19285     19285     19285    ...          19285      19285
2001     21590     21590     21590    ...          21590      21590
2002     23451     23451     23451    ...          23451      23451
2003     27382     27382     27382    ...          27382      27382
2004     29607     29607     29607    ...          29607      29607
2005     34952     34952     34952    ...          34952      34952
2006     37534     37534     37534    ...          37534      37534
2007     39404     39404     39404    ...          39404      39404
2008     34760     34760     34760    ...          34760      34760
2009     31038     31038     31038    ...          31038      31038
2010      9396      9396      9396    ...           9396       9396
2011         1         1         1    ...              1          1

     timb_cov70 timb_cov71 timb_cov72 timb_cov73 timb_cov74 timb_cov75  \
          count      count      count      count      count      count
year
1922          6          6          6          6          6          6
1924          5          5          5          5          5          5
1925          7          7          7          7          7          7
1926         19         19         19         19         19         19
1927         42         42         42         42         42         42
1928         52         52         52         52         52         52
1929         93         93         93         93         93         93
1930         40         40         40         40         40         40
1931         35         35         35         35         35         35
1932         11         11         11         11         11         11
1933          6          6          6          6          6          6
1934         29         29         29         29         29         29
1935         24         24         24         24         24         24
1936         25         25         25         25         25         25
1937         28         28         28         28         28         28
1938         19         19         19         19         19         19
1939         35         35         35         35         35         35
1940         52         52         52         52         52         52
1941         32         32         32         32         32         32
1942         24         24         24         24         24         24
1943         14         14         14         14         14         14
1944         15         15         15         15         15         15
1945         30         30         30         30         30         30
1946         29         29         29         29         29         29
1947         57         57         57         57         57         57
1948         43         43         43         43         43         43
1949         60         60         60         60         60         60
1950         83         83         83         83         83         83
1951         74         74         74         74         74         74
1952         77         77         77         77         77         77
1953        133        133        133        133        133        133
1954        123        123        123        123        123        123
1955        275        275        275        275        275        275
1956        565        565        565        565        565        565
1957        597        597        597        597        597        597
1958        583        583        583        583        583        583
1959        592        592        592        592        592        592
1960        424        424        424        424        424        424
1961        571        571        571        571        571        571
1962        605        605        605        605        605        605
1963        902        902        902        902        902        902
1964        945        945        945        945        945        945
1965       1120       1120       1120       1120       1120       1120
1966       1377       1377       1377       1377       1377       1377
1967       1718       1718       1718       1718       1718       1718
1968       1867       1867       1867       1867       1867       1867
1969       2210       2210       2210       2210       2210       2210
1970       2349       2349       2349       2349       2349       2349
1971       2131       2131       2131       2131       2131       2131
1972       2288       2288       2288       2288       2288       2288
1973       2596       2596       2596       2596       2596       2596
1974       2184       2184       2184       2184       2184       2184
1975       2482       2482       2482       2482       2482       2482
1976       2179       2179       2179       2179       2179       2179
1977       2502       2502       2502       2502       2502       2502
1978       2926       2926       2926       2926       2926       2926
1979       3108       3108       3108       3108       3108       3108
1980       3101       3101       3101       3101       3101       3101
1981       3162       3162       3162       3162       3162       3162
1982       3597       3597       3597       3597       3597       3597
1983       3386       3386       3386       3386       3386       3386
1984       3368       3368       3368       3368       3368       3368
1985       3578       3578       3578       3578       3578       3578
1986       4219       4219       4219       4219       4219       4219
1987       5122       5122       5122       5122       5122       5122
1988       5611       5611       5611       5611       5611       5611
1989       6670       6670       6670       6670       6670       6670
1990       7256       7256       7256       7256       7256       7256
1991       8647       8647       8647       8647       8647       8647
1992       9543       9543       9543       9543       9543       9543
1993      10525      10525      10525      10525      10525      10525
1994      12121      12121      12121      12121      12121      12121
1995      13257      13257      13257      13257      13257      13257
1996      14130      14130      14130      14130      14130      14130
1997      15182      15182      15182      15182      15182      15182
1998      15814      15814      15814      15814      15814      15814
1999      18238      18238      18238      18238      18238      18238
2000      19285      19285      19285      19285      19285      19285
2001      21590      21590      21590      21590      21590      21590
2002      23451      23451      23451      23451      23451      23451
2003      27382      27382      27382      27382      27382      27382
2004      29607      29607      29607      29607      29607      29607
2005      34952      34952      34952      34952      34952      34952
2006      37534      37534      37534      37534      37534      37534
2007      39404      39404      39404      39404      39404      39404
2008      34760      34760      34760      34760      34760      34760
2009      31038      31038      31038      31038      31038      31038
2010       9396       9396       9396       9396       9396       9396
2011          1          1          1          1          1          1

     timb_cov76 timb_cov77
          count      count
year
1922          6          6
1924          5          5
1925          7          7
1926         19         19
1927         42         42
1928         52         52
1929         93         93
1930         40         40
1931         35         35
1932         11         11
1933          6          6
1934         29         29
1935         24         24
1936         25         25

In [28]:
data_sort = data.sort_values('year')
data_sort.head()

,year,timb_avg0,timb_avg1,timb_avg2,timb_avg3,timb_avg4,timb_avg5,timb_avg6,timb_avg7,timb_avg8,...,timb_cov68,timb_cov69,timb_cov70,timb_cov71,timb_cov72,timb_cov73,timb_cov74,timb_cov75,timb_cov76,timb_cov77
22731,1922,46.15136,66.08336,-44.98747,-4.59621,2.79035,0.24898,4.34126,-8.37581,1.12948,...,3.52974,-153.70438,34.93246,25.14792,48.56976,54.46778,-274.15587,16.24013,78.75953,-27.18012
282630,1922,37.58633,-159.68217,160.66121,35.99286,13.20156,9.03191,-24.80241,6.71746,-6.86047,...,-6.63962,-34.35791,-18.00954,16.68930,-10.65305,-4.19842,61.22316,-4.09660,-119.28517,4.75980
22762,1922,39.96727,41.88455,-29.88949,39.92319,26.77335,27.63348,-14.13202,-3.81200,2.78896,...,20.58504,-214.49901,267.35328,396.87548,-5.91930,180.85378,-285.43979,37.66831,111.37413,-7.55992
22761,1922,41.02674,31.16153,11.53418,32.73975,24.29549,20.63578,-2.49337,0.08313,-14.11759,...,1.13195,-140.96426,-108.48106,62.64059,0.65375,154.92370,-78.30312,16.85582,-159.77020,-8.82720
22759,1922,43.68703,39.49153,-14.03862,26.93750,17.67678,11.39290,4.74967,4.51429,-9.64881,...,-13.53449,-53.45490,-43.25854,145.20986,2.00722,125.91492,-81.66189,1.32684,129.29909,-7.95933

In [40]:
data_less_years = data_sort[data_sort['year'] > 1964]
data_less_years = data_less_years[data_less_years['year'] < 2011]
data_less_years.head()

,year,timb_avg0,timb_avg1,timb_avg2,timb_avg3,timb_avg4,timb_avg5,timb_avg6,timb_avg7,timb_avg8,...,timb_cov68,timb_cov69,timb_cov70,timb_cov71,timb_cov72,timb_cov73,timb_cov74,timb_cov75,timb_cov76,timb_cov77
180504,1965,34.44878,-17.56143,37.16011,-8.06183,31.91626,40.64495,-51.83922,9.69663,11.08932,...,65.78889,-392.76322,261.32381,116.74890,43.26091,-53.01305,-109.89799,2.46787,-225.59456,23.88552
57506,1965,45.70380,29.67455,37.85981,1.96353,10.56792,-9.17513,13.18429,11.48913,-3.55091,...,17.95990,-19.46905,112.56604,-7.99781,-13.85670,58.61674,2.75670,8.06404,30.80328,13.14249
180503,1965,37.65798,-2.79729,29.51634,-20.37756,44.02149,36.17114,-38.96125,4.06590,12.66371,...,39.97889,-182.56493,267.62540,89.30427,10.89548,32.27316,-301.90927,11.31802,-69.27096,-24.52177
25639,1965,46.52489,-0.63485,-1.70679,-14.57539,5.86654,-17.86449,0.42215,-6.16082,-2.53274,...,5.77396,-72.14539,-66.85138,49.79943,-0.78326,58.12006,-37.90438,6.10382,29.92346,-9.74033
180502,1965,37.35021,0.54255,45.19308,-33.84218,19.46965,33.02275,-23.98089,9.94354,-12.06169,...,26.92636,190.81648,471.77157,117.83325,7.58932,161.47057,68.66341,3.70337,-165.11797,31.06808

In [34]:
def bootstrap(data, num_to_extract=1000):
    # This function will be applied on each group of instances of the same
    # class in `data`.
    def sampleClass(classgroup):
        cls = classgroup['year'].iloc[0]
        nDesired = num_to_extract
        nRows = len(classgroup)

        nSamples = min(nRows, nDesired)
        return classgroup.sample(nSamples)

    samples = data.groupby('year').apply(sampleClass)
    
    return samples

In [41]:
data_final = bootstrap(data_less_years)

In [42]:
result = data_final.groupby(['year']).agg(['count'])
pd.set_option('display.max_rows', len(result))
print(result)
pd.reset_option('display.max_rows')

     timb_avg0 timb_avg1 timb_avg2 timb_avg3 timb_avg4 timb_avg5 timb_avg6  \
         count     count     count     count     count     count     count
year
1965      1000      1000      1000      1000      1000      1000      1000
1966      1000      1000      1000      1000      1000      1000      1000
1967      1000      1000      1000      1000      1000      1000      1000
1968      1000      1000      1000      1000      1000      1000      1000
1969      1000      1000      1000      1000      1000      1000      1000
1970      1000      1000      1000      1000      1000      1000      1000
1971      1000      1000      1000      1000      1000      1000      1000
1972      1000      1000      1000      1000      1000      1000      1000
1973      1000      1000      1000      1000      1000      1000      1000
1974      1000      1000      1000      1000      1000      1000      1000
1975      1000      1000      1000      1000      1000      1000      1000
1976      1000      1000      1000      1000      1000      1000      1000
1977      1000      1000      1000      1000      1000      1000      1000
1978      1000      1000      1000      1000      1000      1000      1000
1979      1000      1000      1000      1000      1000      1000      1000
1980      1000      1000      1000      1000      1000      1000      1000
1981      1000      1000      1000      1000      1000      1000      1000
1982      1000      1000      1000      1000      1000      1000      1000
1983      1000      1000      1000      1000      1000      1000      1000
1984      1000      1000      1000      1000      1000      1000      1000
1985      1000      1000      1000      1000      1000      1000      1000
1986      1000      1000      1000      1000      1000      1000      1000
1987      1000      1000      1000      1000      1000      1000      1000
1988      1000      1000      1000      1000      1000      1000      1000
1989      1000      1000      1000      1000      1000      1000      1000
1990      1000      1000      1000      1000      1000      1000      1000
1991      1000      1000      1000      1000      1000      1000      1000
1992      1000      1000      1000      1000      1000      1000      1000
1993      1000      1000      1000      1000      1000      1000      1000
1994      1000      1000      1000      1000      1000      1000      1000
1995      1000      1000      1000      1000      1000      1000      1000
1996      1000      1000      1000      1000      1000      1000      1000
1997      1000      1000      1000      1000      1000      1000      1000
1998      1000      1000      1000      1000      1000      1000      1000
1999      1000      1000      1000      1000      1000      1000      1000
2000      1000      1000      1000      1000      1000      1000      1000
2001      1000      1000      1000      1000      1000      1000      1000
2002      1000      1000      1000      1000      1000      1000      1000
2003      1000      1000      1000      1000      1000      1000      1000
2004      1000      1000      1000      1000      1000      1000      1000
2005      1000      1000      1000      1000      1000      1000      1000
2006      1000      1000      1000      1000      1000      1000      1000
2007      1000      1000      1000      1000      1000      1000      1000
2008      1000      1000      1000      1000      1000      1000      1000
2009      1000      1000      1000      1000      1000      1000      1000
2010      1000      1000      1000      1000      1000      1000      1000

     timb_avg7 timb_avg8 timb_avg9    ...     timb_cov68 timb_cov69  \
         count     count     count    ...          count      count
year                                  ...
1965      1000      1000      1000    ...           1000       1000
1966      1000      1000      1000    ...           1000       1000
1967      1000      1000      1000    ...           1000       1000
1968      1000      1000      1000    ...           1000       1000
1969      1000      1000      1000    ...           1000       1000
1970      1000      1000      1000    ...           1000       1000
1971      1000      1000      1000    ...           1000       1000
1972      1000      1000      1000    ...           1000       1000
1973      1000      1000      1000    ...           1000       1000
1974      1000      1000      1000    ...           1000       1000
1975      1000      1000      1000    ...           1000       1000
1976      1000      1000      1000    ...           1000       1000
1977      1000      1000      1000    ...           1000       1000
1978      1000      1000      1000    ...           1000       1000
1979      1000      1000      1000    ...           1000       1000
1980      1000      1000      1000    ...           1000       1000
1981      1000      1000      1000    ...           1000       1000
1982      1000      1000      1000    ...           1000       1000
1983      1000      1000      1000    ...           1000       1000
1984      1000      1000      1000    ...           1000       1000
1985      1000      1000      1000    ...           1000       1000
1986      1000      1000      1000    ...           1000       1000
1987      1000      1000      1000    ...           1000       1000
1988      1000      1000      1000    ...           1000       1000
1989      1000      1000      1000    ...           1000       1000
1990      1000      1000      1000    ...           1000       1000
1991      1000      1000      1000    ...           1000       1000
1992      1000      1000      1000    ...           1000       1000
1993      1000      1000      1000    ...           1000       1000
1994      1000      1000      1000    ...           1000       1000
1995      1000      1000      1000    ...           1000       1000
1996      1000      1000      1000    ...           1000       1000
1997      1000      1000      1000    ...           1000       1000
1998      1000      1000      1000    ...           1000       1000
1999      1000      1000      1000    ...           1000       1000
2000      1000      1000      1000    ...           1000       1000
2001      1000      1000      1000    ...           1000       1000
2002      1000      1000      1000    ...           1000       1000
2003      1000      1000      1000    ...           1000       1000
2004      1000      1000      1000    ...           1000       1000
2005      1000      1000      1000    ...           1000       1000
2006      1000      1000      1000    ...           1000       1000
2007      1000      1000      1000    ...           1000       1000
2008      1000      1000      1000    ...           1000       1000
2009      1000      1000      1000    ...           1000       1000
2010      1000      1000      1000    ...           1000       1000

     timb_cov70 timb_cov71 timb_cov72 timb_cov73 timb_cov74 timb_cov75  \
          count      count      count      count      count      count
year
1965       1000       1000       1000       1000       1000       1000
1966       1000       1000       1000       1000       1000       1000
1967       1000       1000       1000       1000       1000       1000
1968       1000       1000       1000       1000       1000       1000
1969       1000       1000       1000       1000       1000       1000
1970       1000       1000       1000       1000       1000       1000
1971       1000       1000       1000       1000       1000       1000
1972       1000       1000       1000       1000       1000       1000
1973       1000       1000       1000       1000       1000       1000
1974       1000       1000       1000       1000       1000       1000
1975       1000       1000       1000       1000       1000       1000
1976       1000       1000       1000       1000       1000       1000
1977       1000       1000       1000       1000       1000       1000
1978       1000       1000       1000       1000       1000       1000
1979       1000       1000       1000       1000       1000       1000
1980       1000       1000       1000       1000       1000       1000
1981       1000       1000       1000       1000       1000       1000
1982       1000       1000       1000       1000       1000       1000
1983       1000       1000       1000       1000       1000       1000
1984       1000       1000       1000       1000       1000       1000
1985       1000       1000       1000       1000       1000       1000
1986       1000       1000       1000       1000       1000       1000
1987       1000       1000       1000       1000       1000       1000
1988       1000       1000       1000       1000       1000       1000
1989       1000       1000       1000       1000       1000       1000
1990       1000       1000       1000       1000       1000       1000
1991       1000       1000       1000       1000       1000       1000
1992       1000       1000       1000       1000       1000       1000
1993       1000       1000       1000       1000       1000       1000
1994       1000       1000       1000       1000       1000       1000
1995       1000       1000       1000       1000       1000       1000
1996       1000       1000       1000       1000       1000       1000
1997       1000       1000       1000       1000       1000       1000
1998       1000       1000       1000       1000       1000       1000
1999       1000       1000       1000       1000       1000       1000
2000       1000       1000       1000       1000       1000       1000
2001       1000       1000       1000       1000       1000       1000
2002       1000       1000       1000       1000       1000       1000
2003       1000       1000       1000       1000       1000       1000
2004       1000       1000       1000       1000       1000       1000
2005       1000       1000       1000       1000       1000       1000
2006       1000       1000       1000       1000       1000       1000
2007       1000       1000       1000       1000       1000       1000
2008       1000       1000       1000       1000       1000       1000
2009       1000       1000       1000       1000       1000       1000
2010       1000       1000       1000       1000       1000       1000

     timb_cov76 timb_cov77
          count      count
year
1965       1000       1000
1966       1000       1000
1967       1000       1000
1968       1000       1000
1969       1000       1000
1970       1000       1000
1971       1000       1000
1972       1000       1000
1973       1000       1000
1974       1000       1000
1975       1000       1000
1976       1000       1000
1977       1000       1000
1978       1000       1000
1979       1000       1000
1980       1000       1000
1981       1000       1000
1982       1000       1000
1983       1000       1000
1984       1000       1000
1985       1000       1000
1986       1000       1000
1987       1000       1000
1988       1000       1000
1989       1000       1000
1990       1000       1000
1991       1000       1000
1992       1000       1000
1993       1000       1000
1994       1000       1000
1995       1000       1000
1996       1000       1000
1997       1000       1000
1998       1000       1000
1999       1000       1000
2000       1000       1000
2001       1000       1000
2002       1000       1000
2003       1000       1000
2004       1000       1000
2005       1000       1000
2006       1000       1000
2007       1000       1000
2008       1000       1000
2009       1000       1000
2010       1000       1000

[46 rows x 90 columns]

In [43]:
X = data_final.drop('year', axis=1)
Y = data_final['year']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=101)
X_train.info()

pred = mod.predict(X_test)
print("Done Predicting")

keys = []
scores = []

mod = LinearRegression()
mod.fit(X_train, Y_train)
print("Done Training")

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 32200 entries, (1979, 38435) to (2010, 284690)
Data columns (total 90 columns):
timb_avg0     32200 non-null float64
timb_avg1     32200 non-null float64
timb_avg2     32200 non-null float64
timb_avg3     32200 non-null float64
timb_avg4     32200 non-null float64
timb_avg5     32200 non-null float64
timb_avg6     32200 non-null float64
timb_avg7     32200 non-null float64
timb_avg8     32200 non-null float64
timb_avg9     32200 non-null float64
timb_avg10    32200 non-null float64
timb_avg11    32200 non-null float64
timb_cov0     32200 non-null float64
timb_cov1     32200 non-null float64
timb_cov2     32200 non-null float64
timb_cov3     32200 non-null float64
timb_cov4     32200 non-null float64
timb_cov5     32200 non-null float64
timb_cov6     32200 non-null float64
timb_cov7     32200 non-null float64
timb_cov8     32200 non-null float64
timb_cov9     32200 non-null float64
timb_cov10    32200 non-null float64
timb_cov11    32200 non-null float64
timb_cov12    32200 non-null float64
timb_cov13    32200 non-null float64
timb_cov14    32200 non-null float64
timb_cov15    32200 non-null float64
timb_cov16    32200 non-null float64
timb_cov17    32200 non-null float64
timb_cov18    32200 non-null float64
timb_cov19    32200 non-null float64
timb_cov20    32200 non-null float64
timb_cov21    32200 non-null float64
timb_cov22    32200 non-null float64
timb_cov23    32200 non-null float64
timb_cov24    32200 non-null float64
timb_cov25    32200 non-null float64
timb_cov26    32200 non-null float64
timb_cov27    32200 non-null float64
timb_cov28    32200 non-null float64
timb_cov29    32200 non-null float64
timb_cov30    32200 non-null float64
timb_cov31    32200 non-null float64
timb_cov32    32200 non-null float64
timb_cov33    32200 non-null float64
timb_cov34    32200 non-null float64
timb_cov35    32200 non-null float64
timb_cov36    32200 non-null float64
timb_cov37    32200 non-null float64
timb_cov38    32200 non-null float64
timb_cov39    32200 non-null float64
timb_cov40    32200 non-null float64
timb_cov41    32200 non-null float64
timb_cov42    32200 non-null float64
timb_cov43    32200 non-null float64
timb_cov44    32200 non-null float64
timb_cov45    32200 non-null float64
timb_cov46    32200 non-null float64
timb_cov47    32200 non-null float64
timb_cov48    32200 non-null float64
timb_cov49    32200 non-null float64
timb_cov50    32200 non-null float64
timb_cov51    32200 non-null float64
timb_cov52    32200 non-null float64
timb_cov53    32200 non-null float64
timb_cov54    32200 non-null float64
timb_cov55    32200 non-null float64
timb_cov56    32200 non-null float64
timb_cov57    32200 non-null float64
timb_cov58    32200 non-null float64
timb_cov59    32200 non-null float64
timb_cov60    32200 non-null float64
timb_cov61    32200 non-null float64
timb_cov62    32200 non-null float64
timb_cov63    32200 non-null float64
timb_cov64    32200 non-null float64
timb_cov65    32200 non-null float64
timb_cov66    32200 non-null float64
timb_cov67    32200 non-null float64
timb_cov68    32200 non-null float64
timb_cov69    32200 non-null float64
timb_cov70    32200 non-null float64
timb_cov71    32200 non-null float64
timb_cov72    32200 non-null float64
timb_cov73    32200 non-null float64
timb_cov74    32200 non-null float64
timb_cov75    32200 non-null float64
timb_cov76    32200 non-null float64
timb_cov77    32200 non-null float64
dtypes: float64(90)
memory usage: 22.6+ MB
Done Predicting
Done Training

In [45]:
print('Results for: \n')

pred_test = [int(round(i)) for i in pred ]

print(confusion_matrix(Y_test, pred_test))
print(classification_report(Y_test, pred_test))
acc = accuracy_score(Y_test, pred_test)
print(acc)
print('\n' + '\n')
print(mean_absolute_error(Y_test, pred_test))

Results for:

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ...,
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]
             precision    recall  f1-score   support

       1965       0.00      0.00      0.00       326
       1966       0.00      0.00      0.00       286
       1967       0.00      0.00      0.00       288
       1968       0.00      0.00      0.00       286
       1969       0.00      0.00      0.00       302
       1970       0.00      0.00      0.00       303
       1971       0.00      0.00      0.00       319
       1972       0.00      0.00      0.00       306
       1973       0.00      0.00      0.00       297
       1974       0.00      0.00      0.00       311
       1975       0.00      0.00      0.00       304
       1976       0.00      0.00      0.00       310
       1977       0.00      0.00      0.00       288
       1978       0.00      0.00      0.00       311
       1979       0.00      0.00      0.00       291
       1980       0.05      0.00      0.01       291
       1981       0.00      0.00      0.00       267
       1982       0.03      0.00      0.01       306
       1983       0.02      0.00      0.01       317
       1984       0.00      0.00      0.00       290
       1985       0.03      0.01      0.01       306
       1986       0.03      0.01      0.02       291
       1987       0.01      0.01      0.01       299
       1988       0.03      0.03      0.03       304
       1989       0.03      0.04      0.03       289
       1990       0.03      0.05      0.04       314
       1991       0.02      0.05      0.03       297
       1992       0.02      0.05      0.03       294
       1993       0.03      0.10      0.05       304
       1994       0.02      0.07      0.03       288
       1995       0.02      0.07      0.03       300
       1996       0.02      0.08      0.04       317
       1997       0.03      0.09      0.04       310
       1998       0.03      0.09      0.04       303
       1999       0.03      0.11      0.05       304
       2000       0.04      0.12      0.06       312
       2001       0.04      0.08      0.05       299
       2002       0.06      0.12      0.08       293
       2003       0.07      0.10      0.08       312
       2004       0.05      0.05      0.05       291
       2005       0.07      0.05      0.06       286
       2006       0.07      0.03      0.05       298
       2007       0.08      0.02      0.03       315
       2008       0.04      0.01      0.01       304
       2009       0.19      0.02      0.04       283
       2010       0.06      0.00      0.01       288
       2011       0.00      0.00      0.00         0
       2012       0.00      0.00      0.00         0
       2013       0.00      0.00      0.00         0
       2014       0.00      0.00      0.00         0
       2015       0.00      0.00      0.00         0
       2016       0.00      0.00      0.00         0
       2017       0.00      0.00      0.00         0
       2018       0.00      0.00      0.00         0
       2019       0.00      0.00      0.00         0
       2020       0.00      0.00      0.00         0
       2023       0.00      0.00      0.00         0
       2029       0.00      0.00      0.00         0

avg / total       0.03      0.03      0.02     13800

0.0326811594203



11.3652173913

NameError: name 'KMeans' is not defined